services:
  - type: web
    name: insurance-notification-service
    runtime: docker
    rootDir: Backend/Notification-ServiceAPI
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: commit
